ibm.mq:
  queueManager: QueueManager
  channel: DEV.ADMIN.SVRCONN
  connName: localhost(1414)
  user: admin
  password: passw0rd

queue.name: DEV.QUEUE.1

management.endpoints.web.exposure.include: "*"

management.endpoint.health.show-details: ALWAYS
spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    username: usr
    password: pwd
    url: jdbc:mysql://localhost:3306/testbase