ibm.mq:
  queueManager: QueueManager
  channel: DEV.ADMIN.SVRCONN
  connName: localhost(1414)
  user: admin
  password: passw0rd
  pool:
    enabled: true
    max-connections: 10
    use-anonymous-producers: false

queue.name: DEV.QUEUE.1

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: ALWAYS


server:
  port: 8081