ibm.mq:
  queueManager: QueueManager
  channel: DEV.ADMIN.SVRCONN
  connName: localhost(1414)
  user: admin
  password: passw0rd
  pool:
    enabled: true
    max-connections: 15
    use-anonymous-producers: true
    block-if-full-timeout: 30s

queue.name: DEV.QUEUE.1

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: ALWAYS

server:
  port: 8081

spring:
  jms:
    template:
      delivery-mode: non_persistent
      qos-enabled: true