version: '3'
services:
  MQSeries:
    image: ibmcom/mq
    container_name: mqseries
    hostname: mqseries
    ports:
    - 1414:1414
    - 9443:9443
    volumes:
    - ~/mqseries:/mnt/mq
    environment:
    - MQ_QMGR_NAME=QueueManager
    - MQ_ADMIN_PASSWORD=passw0rd
    - LICENSE=accept
  MYSQL:
    image: mysql:8.0.11
    hostname: mysql
    ports:
    - 3306:3306
    volumes:
    - ./.mysql:/var/lib/mysql
    - ./../src/main/resources/database:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_DATABASE=testbase
    - MYSQL_USER=usr
    - MYSQL_PASSWORD=pwd
    - MYSQL_ROOT_PASSWORD=root